/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AccountRouteImport } from './routes/account'
import { Route as MapRouteRouteImport } from './routes/map/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as TopicTopicIdRouteImport } from './routes/topic.$topicId'
import { Route as SubtopicSubtopicIdRouteImport } from './routes/subtopic.$subtopicId'
import { Route as MacrotopicMacrotopicIdRouteImport } from './routes/macrotopic.$macrotopicId'
import { Route as MacroareaMacroareaIdRouteImport } from './routes/macroarea.$macroareaId'
import { Route as MapTopicTopicIdRouteImport } from './routes/map/topic.$topicId'
import { Route as MapSubtopicSubtopicIdRouteImport } from './routes/map/subtopic.$subtopicId'
import { Route as MapMacrotopicMacrotopicIdRouteImport } from './routes/map/macrotopic.$macrotopicId'
import { Route as MapMacroareaMacroAreaIdRouteImport } from './routes/map/macroarea.$macroAreaId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRouteRoute = MapRouteRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapRouteRoute,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubtopicSubtopicIdRoute = SubtopicSubtopicIdRouteImport.update({
  id: '/subtopic/$subtopicId',
  path: '/subtopic/$subtopicId',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrotopicMacrotopicIdRoute = MacrotopicMacrotopicIdRouteImport.update({
  id: '/macrotopic/$macrotopicId',
  path: '/macrotopic/$macrotopicId',
  getParentRoute: () => rootRouteImport,
} as any)
const MacroareaMacroareaIdRoute = MacroareaMacroareaIdRouteImport.update({
  id: '/macroarea/$macroareaId',
  path: '/macroarea/$macroareaId',
  getParentRoute: () => rootRouteImport,
} as any)
const MapTopicTopicIdRoute = MapTopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => MapRouteRoute,
} as any)
const MapSubtopicSubtopicIdRoute = MapSubtopicSubtopicIdRouteImport.update({
  id: '/subtopic/$subtopicId',
  path: '/subtopic/$subtopicId',
  getParentRoute: () => MapRouteRoute,
} as any)
const MapMacrotopicMacrotopicIdRoute =
  MapMacrotopicMacrotopicIdRouteImport.update({
    id: '/macrotopic/$macrotopicId',
    path: '/macrotopic/$macrotopicId',
    getParentRoute: () => MapRouteRoute,
  } as any)
const MapMacroareaMacroAreaIdRoute = MapMacroareaMacroAreaIdRouteImport.update({
  id: '/macroarea/$macroAreaId',
  path: '/macroarea/$macroAreaId',
  getParentRoute: () => MapRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/bookmarks': typeof BookmarksRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/tutorial': typeof TutorialRoute
  '/upload': typeof UploadRoute
  '/macroarea/$macroareaId': typeof MacroareaMacroareaIdRoute
  '/macrotopic/$macrotopicId': typeof MacrotopicMacrotopicIdRoute
  '/subtopic/$subtopicId': typeof SubtopicSubtopicIdRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/map/': typeof MapIndexRoute
  '/map/macroarea/$macroAreaId': typeof MapMacroareaMacroAreaIdRoute
  '/map/macrotopic/$macrotopicId': typeof MapMacrotopicMacrotopicIdRoute
  '/map/subtopic/$subtopicId': typeof MapSubtopicSubtopicIdRoute
  '/map/topic/$topicId': typeof MapTopicTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookmarks': typeof BookmarksRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/tutorial': typeof TutorialRoute
  '/upload': typeof UploadRoute
  '/macroarea/$macroareaId': typeof MacroareaMacroareaIdRoute
  '/macrotopic/$macrotopicId': typeof MacrotopicMacrotopicIdRoute
  '/subtopic/$subtopicId': typeof SubtopicSubtopicIdRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/map': typeof MapIndexRoute
  '/map/macroarea/$macroAreaId': typeof MapMacroareaMacroAreaIdRoute
  '/map/macrotopic/$macrotopicId': typeof MapMacrotopicMacrotopicIdRoute
  '/map/subtopic/$subtopicId': typeof MapSubtopicSubtopicIdRoute
  '/map/topic/$topicId': typeof MapTopicTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/bookmarks': typeof BookmarksRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/tutorial': typeof TutorialRoute
  '/upload': typeof UploadRoute
  '/macroarea/$macroareaId': typeof MacroareaMacroareaIdRoute
  '/macrotopic/$macrotopicId': typeof MacrotopicMacrotopicIdRoute
  '/subtopic/$subtopicId': typeof SubtopicSubtopicIdRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/map/': typeof MapIndexRoute
  '/map/macroarea/$macroAreaId': typeof MapMacroareaMacroAreaIdRoute
  '/map/macrotopic/$macrotopicId': typeof MapMacrotopicMacrotopicIdRoute
  '/map/subtopic/$subtopicId': typeof MapSubtopicSubtopicIdRoute
  '/map/topic/$topicId': typeof MapTopicTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/account'
    | '/bookmarks'
    | '/help'
    | '/leaderboard'
    | '/notifications'
    | '/settings'
    | '/tutorial'
    | '/upload'
    | '/macroarea/$macroareaId'
    | '/macrotopic/$macrotopicId'
    | '/subtopic/$subtopicId'
    | '/topic/$topicId'
    | '/map/'
    | '/map/macroarea/$macroAreaId'
    | '/map/macrotopic/$macrotopicId'
    | '/map/subtopic/$subtopicId'
    | '/map/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bookmarks'
    | '/help'
    | '/leaderboard'
    | '/notifications'
    | '/settings'
    | '/tutorial'
    | '/upload'
    | '/macroarea/$macroareaId'
    | '/macrotopic/$macrotopicId'
    | '/subtopic/$subtopicId'
    | '/topic/$topicId'
    | '/map'
    | '/map/macroarea/$macroAreaId'
    | '/map/macrotopic/$macrotopicId'
    | '/map/subtopic/$subtopicId'
    | '/map/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/account'
    | '/bookmarks'
    | '/help'
    | '/leaderboard'
    | '/notifications'
    | '/settings'
    | '/tutorial'
    | '/upload'
    | '/macroarea/$macroareaId'
    | '/macrotopic/$macrotopicId'
    | '/subtopic/$subtopicId'
    | '/topic/$topicId'
    | '/map/'
    | '/map/macroarea/$macroAreaId'
    | '/map/macrotopic/$macrotopicId'
    | '/map/subtopic/$subtopicId'
    | '/map/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRouteRoute: typeof MapRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  BookmarksRoute: typeof BookmarksRoute
  HelpRoute: typeof HelpRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  TutorialRoute: typeof TutorialRoute
  UploadRoute: typeof UploadRoute
  MacroareaMacroareaIdRoute: typeof MacroareaMacroareaIdRoute
  MacrotopicMacrotopicIdRoute: typeof MacrotopicMacrotopicIdRoute
  SubtopicSubtopicIdRoute: typeof SubtopicSubtopicIdRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof MapRouteRoute
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subtopic/$subtopicId': {
      id: '/subtopic/$subtopicId'
      path: '/subtopic/$subtopicId'
      fullPath: '/subtopic/$subtopicId'
      preLoaderRoute: typeof SubtopicSubtopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macrotopic/$macrotopicId': {
      id: '/macrotopic/$macrotopicId'
      path: '/macrotopic/$macrotopicId'
      fullPath: '/macrotopic/$macrotopicId'
      preLoaderRoute: typeof MacrotopicMacrotopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macroarea/$macroareaId': {
      id: '/macroarea/$macroareaId'
      path: '/macroarea/$macroareaId'
      fullPath: '/macroarea/$macroareaId'
      preLoaderRoute: typeof MacroareaMacroareaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/topic/$topicId': {
      id: '/map/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/map/topic/$topicId'
      preLoaderRoute: typeof MapTopicTopicIdRouteImport
      parentRoute: typeof MapRouteRoute
    }
    '/map/subtopic/$subtopicId': {
      id: '/map/subtopic/$subtopicId'
      path: '/subtopic/$subtopicId'
      fullPath: '/map/subtopic/$subtopicId'
      preLoaderRoute: typeof MapSubtopicSubtopicIdRouteImport
      parentRoute: typeof MapRouteRoute
    }
    '/map/macrotopic/$macrotopicId': {
      id: '/map/macrotopic/$macrotopicId'
      path: '/macrotopic/$macrotopicId'
      fullPath: '/map/macrotopic/$macrotopicId'
      preLoaderRoute: typeof MapMacrotopicMacrotopicIdRouteImport
      parentRoute: typeof MapRouteRoute
    }
    '/map/macroarea/$macroAreaId': {
      id: '/map/macroarea/$macroAreaId'
      path: '/macroarea/$macroAreaId'
      fullPath: '/map/macroarea/$macroAreaId'
      preLoaderRoute: typeof MapMacroareaMacroAreaIdRouteImport
      parentRoute: typeof MapRouteRoute
    }
  }
}

interface MapRouteRouteChildren {
  MapIndexRoute: typeof MapIndexRoute
  MapMacroareaMacroAreaIdRoute: typeof MapMacroareaMacroAreaIdRoute
  MapMacrotopicMacrotopicIdRoute: typeof MapMacrotopicMacrotopicIdRoute
  MapSubtopicSubtopicIdRoute: typeof MapSubtopicSubtopicIdRoute
  MapTopicTopicIdRoute: typeof MapTopicTopicIdRoute
}

const MapRouteRouteChildren: MapRouteRouteChildren = {
  MapIndexRoute: MapIndexRoute,
  MapMacroareaMacroAreaIdRoute: MapMacroareaMacroAreaIdRoute,
  MapMacrotopicMacrotopicIdRoute: MapMacrotopicMacrotopicIdRoute,
  MapSubtopicSubtopicIdRoute: MapSubtopicSubtopicIdRoute,
  MapTopicTopicIdRoute: MapTopicTopicIdRoute,
}

const MapRouteRouteWithChildren = MapRouteRoute._addFileChildren(
  MapRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRouteRoute: MapRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  BookmarksRoute: BookmarksRoute,
  HelpRoute: HelpRoute,
  LeaderboardRoute: LeaderboardRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  TutorialRoute: TutorialRoute,
  UploadRoute: UploadRoute,
  MacroareaMacroareaIdRoute: MacroareaMacroareaIdRoute,
  MacrotopicMacrotopicIdRoute: MacrotopicMacrotopicIdRoute,
  SubtopicSubtopicIdRoute: SubtopicSubtopicIdRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
